export const MockState = {
  keptStateMock:[
    {
      id: 1,
      actName: 'name',
      actId: 11,
      actIcon: 'plus',
      maxCount: 11,
      quantity: 11,
      save: false,
      active: true,
      right: 5,
      fault: 6
    },
    {
      id: 2,
      actName: 'Сложение',
      actId: 22,
      actIcon: 'plus',
      maxCount: 22,
      quantity: 20,
      save: true,
      active: false,
      right: 10,
      fault: 12
    },
    {
      id: 3,
      actName: 'Сложение',
      actId: 22,
      actIcon: 'plus',
      maxCount: 22,
      quantity: 20,
      save: true,
      active: false,
      right: 10,
      fault: 12
    },
    // {
    //   id: 4,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 5,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 6,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 7,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 8,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 9,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 10,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 11,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 12,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 13,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 14,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 15,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 16,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 17,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
    // {
    //   id: 18,
    //   actName: 'Сложение',
    //   actId: 22,
    //   actIcon: 'plus',
    //   maxCount: 22,
    //   quantity: 20,
    //   save: true,
    //   active: false,
    //   right: 10,
    //   fault: 12
    // },
  ] 
}